name: Release

on:
  push:
  pull_request:
    branches:
      - master
    tags:
      - '*.*.*'

jobs:
  deploy:
    runs-on: ubuntu-18.04

    steps:
      - name: set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            echo $RELEASE_VERSION
            sh build.sh $RELEASE_VERSION
